name: ELT Menor Preco Bronze (Azure)

on:
  workflow_dispatch: # Permite rodar manualmente no botão
  schedule:
    - cron: '0 11 * * *' # Roda todo dia às 08h (horário de Brasília)

jobs:
  extract_and_load:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Acelera a execução cacheando as bibliotecas

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install polars pyarrow requests azure-storage-blob python-dotenv boto3

      - name: Executar Script de Extração e Envio para Azure
        # Injeta a senha segura como variável de ambiente apenas durante a execução
        env:
          AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
          STORAGE_PROVIDER: ${{ secrets.STORAGE_PROVIDER }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PYTHONUNBUFFERED: "1" # Isso aqui força o log em tempo real
        run: python tasks_python/bronze/bronze_menor_preco.py